version: 2.1
jobs:
  build:
    working_directory: ~/viva-angular
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      # Log
      - run: 
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      # Restore local dependencies from cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      # Install dependencies
      - run:
          name: Install local dependencies
          command: |
              apk add  --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.7/main/ nodejs=8.9.3-r1              
              npm install
             
      #Cache Local dependencies
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths: 
             - node_modules