version: 2.1
jobs:
  build:
    working_directory: ~/viva-angular
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - setup_remote_docker
      # Log
      - run: 
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      # Restore local dependencies from cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      # Install dependencies
      - run:
          name: Install local dependencies
          command: npm install
      - run:
          name: Deploy to Docker HUB
          command: |
             docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
             docker tag viva-angular_angularapp $DOCKER_HUB_USER_ID/viva-angular:$CIRCLE_SHA1
             docker tag viva-angular_angularapp $DOCKER_HUB_USER_ID/viva-angular:latest
             docker push $DOCKER_HUB_USER_ID/viva-angular:$CIRCLE_SHA1
             docker push $DOCKER_HUB_USER_ID/viva-angular:latest
        
      #Cache Local dependencies
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths: 
             - node_modules