version: 2.1
jobs:
  build:
    working_directory: ~/viva-angular
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      # Log
      - run: 
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      # Restore local dependencies from cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      # Install dependencies
      - run:
          name: Install local dependencies
          command: |
              apk add  --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.7/main/ nodejs=8.9.3-r1
              apk add  --no-cache py-pip=9.0.0-r1
              pip install docker-compose==1.15.0     
              npm install
      # Run test
      - run:
          name: Run tests
          command: |
              docker-compose up -d
              echo "Docker Ps...."
              docker ps
              echo "Docker Images...."
              docker images
      # Deploy to Docker Hub
      - run:
          name: Deploy to Docker HUB
          command: |
              docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
              docker tag vivaangular_angularapp $DOCKER_HUB_USER_ID/viva-angular:$CIRCLE_SHA1
              docker tag vivaangular_angularapp $DOCKER_HUB_USER_ID/viva-angular:latest
              docker push $DOCKER_HUB_USER_ID/viva-angular:$CIRCLE_SHA1
              docker push $DOCKER_HUB_USER_ID/viva-angular:latest             
             
      #Cache Local dependencies
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths: 
             - node_modules